version: '3.1'

services:
  zookeeper:
    image: 6b9b99b28acf
    container_name: zookeeper
    ports:
      - '2181:2181'
  app:
    image: '5e1ddf327ef9'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - KAFKA_URL=kafka:9092
      - DB_USER=dmitrij
      - DB_PASSWORD=1709
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
      - kafka
  db:
    image: 'postgres'
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=dmitrij
      - POSTGRES_PASSWORD=1709
  consumer:
    image: e86789a3670e
    container_name: consumer
    environment:
    - KAFKA_URL=kafka:9092
    depends_on:
      - kafka
    expose:
      - 8000
    ports:
      - '8000:8000'
  kafka:
    image: 490cb452bb47
    container_name: kafka
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
