version: '3.1'

services:
  app:
    image: '663a33e7b11f'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
     - DB_USER=dmitrij
     - DB_PASSWORD=1709
     - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=dmitrij
      - POSTGRES_PASSWORD=1709
